/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package myscript;

import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URI;

/**
 *
 * @author
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        super("MyScript");
        initComponents();
        this.getContentPane().setBackground(Color.blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jButton1.setText("Create Script");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View / Edit Script");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Execute Script");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("View Generated HTML");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("About Us");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(26, 26, 26)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 51)));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SCRIPT EXECUTOR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("@copyright Graphic Era University");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        jTextArea1.setEditable(false);
        jTextArea1.setVisible(false);

        String str = " ";
        String file = "temp.html";
        try
        {
            File f = new File(file);
            char buff[]= new char[(int)f.length()];
            FileReader fr = new FileReader(file);
            fr.read(buff) ;
            str = new String(buff);
        }
        catch(Exception e)
        {

        }
        jTextArea1.setVisible(true);
        jTextArea1.setEditable(false);
        jTextArea1.setText(str);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        jTextArea1.setEditable(true);
        jTextArea1.setVisible(false);

        String file = JOptionPane.showInputDialog("Enter File Name");
        String str= "";
        int loc = -1;
        if(file.length()!=0)
        {
            if(file.indexOf(".ms")==-1)
            {
                if((loc=file.indexOf("."))!=-1)
                {
                    JOptionPane.showMessageDialog(null, "ERROR OCCURED : Invalid File Name. Allowed Extention is .ms");
                    return;
                }
                else
                {
                    file = file+".ms";
                }
            }
            try
            {
                FileWriter fw = new FileWriter(file);

                fw.write("<script language=ms>\n\n\n</script>");
                fw.close();

                // open file to display in text area
                File f = new File(file);
                char buff[]= new char[(int)f.length()];
                FileReader fr = new FileReader(file);
                fr.read(buff) ;
                str = new String(buff);
                jTextArea1.setText(str);
                jTextArea1.setVisible(true);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "ERROR OCCURED : Please Try Again .......");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        jTextArea1.setText("");
        jTextArea1.setEditable(true);
        jTextArea1.setVisible(false);

        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File("."));

        //set file ext to ms
        FileNameExtensionFilter filter = new FileNameExtensionFilter("MyScript Files", "ms");
        fc.setFileFilter(filter);

        int returnVal = fc.showDialog(this, "Select Script File");

        if (returnVal == JFileChooser.APPROVE_OPTION)
        {
            File file = fc.getSelectedFile();
            if(file.exists())
            {
                char buff[]= new char[(int)file.length()];
                try
                {
                    FileReader fr = new FileReader(file);
                    fr.read(buff) ;
                    String str = new String(buff);
                    jTextArea1.setText(str);
                    jTextArea1.setVisible(true);
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "ERROR OCCURED : Unable to open file.");
                }
                //txtDest.setText(getDest(file.getPath()));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "ERROR OCCURED : File does not exist.");
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // ask script file

        jTextArea1.setText("");
        jTextArea1.setVisible(false);

        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File("."));

        //set file ext to ms
        FileNameExtensionFilter filter = new FileNameExtensionFilter("MyScript Files", "ms");
        fc.setFileFilter(filter);

        int returnVal = fc.showDialog(this, "Select Script File");

        if (returnVal == JFileChooser.APPROVE_OPTION)
        {
            String fhtml = "temp.html";
            File file = fc.getSelectedFile();
            if(file.exists())
            {

                try
                {
                    //fhtml = file.getName();
                    //fhtml =  fhtml.substring(0, fhtml.indexOf(".")) + ".html";

                    String str = fileToStr(file.getAbsolutePath());

                    str = parse(str);

                    FileWriter fw = new FileWriter("Temp.java");
                    fw.write(str);
                    fw.close();


                    // compile generated java file

                    try
                    {
                        runProcess("javac Temp.java");
                        runProcess("java Temp");
                    }
                    catch (Exception e)
                    {
                        e.printStackTrace();
                    }

                    // launch browser

                    if(Desktop.isDesktopSupported())
                    {
                        try
                        {
                            Desktop.getDesktop().browse(new URI(fhtml));
                        }
                        catch(Exception e)
                        {
                            JOptionPane.showMessageDialog(null, "ERROR OCCURED : Unable to Launch Web Browser.");
                        }
                    }

                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "ERROR OCCURED : Unable to open file." );
                }
                //txtDest.setText(getDest(file.getPath()));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "ERROR OCCURED : File does not exist.");
            }
        }


    }//GEN-LAST:event_jButton3ActionPerformed
private  void runProcess(String command) throws Exception {
    Process pro = Runtime.getRuntime().exec(command);
    pro.waitFor();
  }

 String replaceAllOcc(String s, String find, String replace)
 {
	return s.replace(find,replace);
 }
String fileToStr(String file)
{
    String str=null;
    try
    {
        BufferedReader bufferedReader = new BufferedReader(new FileReader(file));

        StringBuffer stringBuffer = new StringBuffer();
        String line = null;

        while((line =bufferedReader.readLine())!=null)
        {
            stringBuffer.append(line).append("\n");
        }
        str = stringBuffer.toString();
    }
    catch(Exception e)
    {

    }
    return (str);
 }
	String placeCurlyBraceExc(String str,String start)
	{
		int count=0,i, loc=-1;

                StringBuffer sb = new StringBuffer(str);
		while( (loc = sb.indexOf(start, loc+1)) != -1)
                {

                    count=0;
                    loc = sb.indexOf("(",loc+1);
                    count++;
                    i=loc+1;
                    while(count!=0)
                    {
			if(sb.charAt(i)==')')
				count--;
			if(sb.charAt(i)=='(')
				count++;
			i++;
                    }
                    sb.insert(i," throws Exception {");
                }
		return sb.toString();
	}

	String placeCurlyBrace(String str,String start)
	{
		int count=0,i, loc=-1;

                StringBuffer sb = new StringBuffer(str);
		while( (loc = sb.indexOf(start, loc+1)) != -1)
                {

                    count=0;
                    loc = sb.indexOf("(",loc+1);
                    count++;
                    i=loc+1;
                    while(count!=0)
                    {
			if(sb.charAt(i)==')')
				count--;
			if(sb.charAt(i)=='(')
				count++;
			i++;
                    }
                    sb.insert(i,"{");
                }
		return sb.toString();
	}


 String parse(String str)
 {

    str =  replaceAllOcc(str, "<script Language=ms>", "import java.io.*;  class Temp{ static FileWriter fw = null;");
    str =  replaceAllOcc(str, "</script>", " } ");

    str =  replaceAllOcc(str, "@begin", "public static void main(String args[]){ try{fw = new FileWriter(\"temp.html\");fw.write(\"<HTML><HEAD><TITLE></TITLE></HEAD><BODY bgcolor=blue><font color=white><br><marquee><H1><B><I>MyScript - Script Executor</B></I></H1></marquee>\");");
    str =  replaceAllOcc(str, "@end", " fw.write(\"</font></BODY></HTML>\");fw.close();}catch(Exception e){System.out.println(\"ERROR : \" + e);} } ");

    str =  replaceAllOcc(str, "@hprint", " fw.write");

    str =  replaceAllOcc(str, "@funiend", " } ");
    str =  placeCurlyBraceExc(str,"@funi");
    str =  replaceAllOcc(str, "@funi", " static int ");


    str =  replaceAllOcc(str, "@subend", " } ");
    str =  placeCurlyBraceExc(str,"@sub");
    str =  replaceAllOcc(str, "@sub", " static void ");

    str =  replaceAllOcc(str, "@forend", "}");
    str =  placeCurlyBrace(str,"@for");
    str =  replaceAllOcc(str, "@for", "for");

    str =  replaceAllOcc(str, "@whilend", "}");
    str =  placeCurlyBrace(str,"@while");
    str =  replaceAllOcc(str, "@while", "while");

    str =  replaceAllOcc(str, "@else", "}else{");
    str =  replaceAllOcc(str, "@ifend", "}");
    str =  placeCurlyBrace(str,"@if");
    str =  replaceAllOcc(str, "@if", "if");

    str =  replaceAllOcc(str, "@i", " int ");
    str =  replaceAllOcc(str, "@b", " boolean ");
    str =  replaceAllOcc(str, "@f", " float ");
    str =  replaceAllOcc(str, "@c", " char ");

    return str;
}

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        jTextArea1.setText("Created By : Shubham Khanna & Shubham Anand");
        jTextArea1.setEditable(false);
        jTextArea1.setVisible(true);

    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gui g = new gui();
                g.jTextArea1.setVisible(false);
                g.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
